global:
  resolve_timeout: 5m

route:
  receiver: 'email'
    
receivers:
  - name: 'email'
    email_configs:
    - to: 'hek_v@mail.ru'
      from: 'test.alertov@yandex.ru'
      smarthost: 'smtp.yandex.ru:587'
      auth_username: 'test.alertov'
      auth_password: 'pas'
      require_tls: true

# to : Адрес получателя электронной почты.
# from : Адрес отправителя электронной почты.
# smarthost : SMTP-сервер для отправки писем (в формате адрес:порт).
# auth_username : Имя пользователя для аутентификации на SMTP-сервере.
# auth_password : Пароль для аутентификации на SMTP-сервере.
# require_tls : Флаг, указывающий, требуется ли использование TLS для безопасного соединения с SMTP-сервером.