FROM jupyterhub/jupyterhub:latest
WORKDIR /srv/jupyterhubtest

RUN mkdir -p /srv/jupyterhubtest/data && \
    chown -R 1000:100 /srv/jupyterhubtest 
RUN python3 -m pip install --no-cache-dir \
    psycopg2-binary \    
    dockerspawner \
    jupyterhub-nativeauthenticator

COPY jupyterhub_config.py /srv/jupyterhubtest/jupyterhub_config.py
CMD ["jupyterhub", "-f", "/srv/jupyterhubtest/jupyterhub_config.py"]

    

