global:
  scrape_interval: '15s'
  evaluation_interval: '15s'
    
scrape_configs:
  - job_name: 'jupyterhubtest'
    static_configs:
      - targets: ['jupyterhubtest:8000']
   
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exportertest:9100']
 
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisortest:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanagertest:9093']
        
rule_files:
  - '/etc/prometheus/alert.rules.yml'
